### PR TITLE
Doc circle.yml config to put results in the reports folder

### PR DESCRIPTION
**Pull request by bf4**

### CODE REVIEW

**Comment by bf4** [comment]
Failure not related to PR

**Comment by sandcastle** [comment]
@bf4 Yep, looks like its related to dependencies causing breaking changes

**Comment by bf4** [comment]
So merge anyway?

**Comment by dustyjewett** [comment]
Ugh, I hate these comments... but... "bump"... I came here after looking into a bunch of circle docs.... this would have saved me several hours if this had been merged.

**Comment by bf4** [comment]
@sandcastle any blockers to merging this? Can I or someone else help?

**Comment by sandcastle** [comment]
Done, we can fix up the deps issue at a later date (#2).

**Comment by bf4** [comment]
Awesome!  I'm not using mocha anymore (or even doing js), but may take a crack at fixing the build and am happy to help review prs

B mobile phone

**Pull request merged**
